require "Configs.Text.Buff_Text"
Buff = {
	[101] = {
		id = 101,
		type = 1,
		triggerInterval = -1,
		desc = Buff_Text.desc_4,
		effectPath = Buff_Text.effectPath_4,
		iconPath = Buff_Text.iconPath_4,
	},
	[102] = {
		id = 102,
		type = 1,
		triggerInterval = -1,
		desc = Buff_Text.desc_5,
		effectPath = Buff_Text.effectPath_5,
		iconPath = Buff_Text.iconPath_5,
	},
	[103] = {
		id = 103,
		type = 2,
		triggerInterval = -1,
		desc = Buff_Text.desc_6,
		effectPath = Buff_Text.effectPath_6,
		iconPath = Buff_Text.iconPath_6,
	},
	[104] = {
		id = 104,
		type = 3,
		triggerInterval = 0.2,
		desc = Buff_Text.desc_7,
		effectPath = Buff_Text.effectPath_7,
		iconPath = Buff_Text.iconPath_7,
	},
	[105] = {
		id = 105,
		type = 3,
		triggerInterval = 0.2,
		desc = Buff_Text.desc_8,
		effectPath = Buff_Text.effectPath_8,
		iconPath = Buff_Text.iconPath_8,
	},
	[106] = {
		id = 106,
		type = 4,
		triggerInterval = -1,
		desc = Buff_Text.desc_9,
		effectPath = Buff_Text.effectPath_9,
		iconPath = Buff_Text.iconPath_9,
	},
	[107] = {
		id = 107,
		type = 4,
		triggerInterval = -1,
		desc = Buff_Text.desc_10,
		effectPath = Buff_Text.effectPath_10,
		iconPath = Buff_Text.iconPath_10,
	},
	[108] = {
		id = 108,
		type = 5,
		triggerInterval = -1,
		desc = Buff_Text.desc_11,
		effectPath = Buff_Text.effectPath_11,
		iconPath = Buff_Text.iconPath_11,
	},
	[109] = {
		id = 109,
		type = 5,
		triggerInterval = -1,
		desc = Buff_Text.desc_12,
		effectPath = Buff_Text.effectPath_12,
		iconPath = Buff_Text.iconPath_12,
	},
}
Buff.Count = 9