require "Configs.Text.Summon_Text"
--***********************代码由工具生成***********************--
Summon = {
	[101] = {
		id = 101,
		spawnCount = 10,
		spawnInterval = 0.3,
		moveSpeed = 8,
		castTarget = 4,
		targetMode = 2,
		compare = 4,
		targetValue = nil,
		targetNum = 1,
		isContinueFollow = false,
		isRandomStartPoint = true,
		isRandomRoute = true,
		assetPath = Summon_Text.assetPath_4,
	},
	[102] = {
		id = 102,
		spawnCount = 10,
		spawnInterval = 0.3,
		moveSpeed = nil,
		castTarget = nil,
		targetMode = nil,
		compare = nil,
		targetValue = nil,
		targetNum = nil,
		isContinueFollow = true,
		isRandomStartPoint = false,
		isRandomRoute = false,
		assetPath = Summon_Text.assetPath_5,
	},
	[103] = {
		id = 103,
		spawnCount = nil,
		spawnInterval = nil,
		moveSpeed = nil,
		castTarget = nil,
		targetMode = nil,
		compare = nil,
		targetValue = nil,
		targetNum = nil,
		isContinueFollow = nil,
		isRandomStartPoint = nil,
		isRandomRoute = nil,
		assetPath = Summon_Text.assetPath_6,
	},
}
Summon.Count = 3