GlobalDefine = {}
GlobalDefine.UIPath = "Assets/Resource/UI/"
GlobalDefine.OnePId = 1
GlobalDefine.TwoPId = 2
GlobalDefine.OnePName = "1P"
GlobalDefine.TwoPName = "2P"
GlobalDefine.ScenePath = "Assets/Resource/Scenes/"
GlobalDefine.BlueTeam = 1   --蓝队id
GlobalDefine.RedTeam = 2    --红队id