GlobalDefine = {}
GlobalDefine.UIPath = "Assets/Resource/UI/"
GlobalDefine.OnePId = 1
GlobalDefine.TwoPId = 2
GlobalDefine.OnePName = "1P"
GlobalDefine.TwoPName = "2P"
GlobalDefine.ScenePath = "Assets/Resource/Scenes/"
GlobalDefine.AtlasPath = "Assets/Resource/Atlas/"
GlobalDefine.BlueTeam = 1   --蓝队id
GlobalDefine.RedTeam = 2    --红队id
GlobalDefine.BeatBackRepair = 0.1  --击退修正值
GlobalDefine.GetHurtBuff = 110  --直接扣血buff
GlobalDefine.WeaponIconHeight = 100